# Clear Enviromment
if(!is.null(dev.list())) dev.off()
cat("\014")
rm(list = ls())
options(scipen = 9)

# setting the current directory
setwd('C:/Users/RXPCOMPUTER/Source/RProjects/dataanalyticswithr')


# load librar
# The ggplot2 is developed based on a Grammar of Graphics (hence the “gg”), 
# a modular approach that builds complex graphics by adding layers. 
# Intuitive yet powerful, ggplot2 is becoming increasingly popular.

# Install the package. You can also do it through the Packages Tab
install.packages("ggplot2")
install.packages("pheatmap")

# define a canvas
library(ggplot2)
library(pheatmap)


df <- read.csv('iris.csv')
# exploratory data analysis (EDA)

PL <- df$petal_length
PW <- df$petal_width
SP <- as.factor(df$species)

# define a canavas
ggplot(data = df) +
  aes(x = PL, y = PW) +
  geom_point(aes(color = SP, shape = SP)) + # change color & symbol type
  geom_smooth(method = lm) + # add trend line
  annotate("text", x = 5, y = 0.5, label = "R = 0.96") + # annotate with text
  xlab("Petal length (cm)") + # x-axis labels
  ylab("Petal width (cm)") +  # y-axis labels
  ggtitle("Correlation between petal length and width") # title
  

# Box plots can be generated by ggplot
ggplot(data = df) +
  aes(x = SP, y = PL, color = SP) +
  geom_boxplot() +
  geom_jitter(position = position_jitter(0.2)) +
  xlab("Species") + # x-axis labels
  ylab("Petal Length (cm)")   # y-axis labels
  # ggtitle("Correlation between petal length and width")

# Desitiy plot
ggplot(data = df) +
  aes(x = PL, fill = SP) +
  geom_density(alpha = 0.3)

# Desitiy plot
# ggplot(data = df) +
#   aes(x = PL, fill = SP) +
#   geom_density(alpha = 0.3) +
#   facet_wrap(~SP, nrow =3)

# The dynamite plots must die!”,
ggplot(data = df) +
  aes(x = SP, y = PW, fill = SP) +
  stat_summary(geom = "bar", fun = "mean") +
  stat_summary(geom = "errorbar", fun.data = "mean_se", width = .3) +
  xlab("Species") + # x-axis labels
  ylab("Sepal Width ")  + # y-axis labels
  ggtitle("The dynamite plots")

# Hierarchical clustering and heat map
ma <- as.matrix(df[, 1:4])
disMatarix <- dist(ma)
plot(hclust(disMatarix))

# Heat maps
heatmap(ma,
        scale = "column",
        RowSideColors = rainbow(3)[SP])

# Heatmap for iris flower dataset
row.names(ma) <- row.names(df) # convert to matrix
pheatmap(ma,
         scale = "column",
         clustering_method = "average", # assign row names in the matrix
         annotation_row = df[, 5, drop = FALSE],
         show_rownames = FALSE)







